### ISSUE TITLE
Search: multiple entries from multilangual products

### ISSUE THREAD

**Issue by paulhaem** [ContaoBlackForest/contao-isotope-product-list#1]
Hey there,
I am really happy that someone released a stable package for the use of products in articles. :+1: 

I had some issues while adding the products via search. There were multiple entries for every translation of the product. The fallback product had an SKU, the others didnt. And so when I accidentally added a translated version of a product, it didn't show up in the frontend. Its quite confusing to see duplicate entries (with two active languages) and it can get quite the nuisance with even more languages. Wouldn't it be good to just display products where the `pid` equals 0?

**Comment by baumannsven** [comment]
Thanks for your gratulation. 
I show which can i do for translated product.

**Comment by baumannsven** [comment]
So i have filter the search. Now it list no translated product and no variants.

**Comment by paulhaem** [comment]
Wow, thanks a lot. :+1: 
But why did you disable the search for variants? It is quite useful to select variants in content elements so the e.g. select fields are preselected.

EDIT: I just figured out that products with `pid` equals 0 can never be a variant. Sorry for suggesting that.

**Comment by paulhaem** [comment]
By changing `$config->setConditionExpr('pid = 0 AND language=\'\'')` to `$config->setConditionExpr('language=\'\'')` I made it work for variants for a current project.

**Comment by baumannsven** [comment]
Okay i think for the search configuration, i make two checkboxes for switch on list variants and translated products.

**Comment by baumannsven** [comment]
@paulhaem I have implemented the change
